- name: Playbook default iniciando implantação
  hosts: all
  user: 
  become: true
  become_user: root
  gather_facts: yes
  roles:
    - reconfigura-host
    - common
    - instala-bbb
    - nfs
    - backgrounds
    # - extra
    - restart
    - test

