---
- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: docker

- name: Instalando BigBlueButton - Script
#  shell: sudo wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -g -s '{{ DOMINIO }}' -e '{{ EMAIL }}'
  shell: sudo wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s '{{ DOMINIO }}' -e '{{ EMAIL }}' -c '{{ TURN_SERVER }}:{{ TURN_SECRET }}'

- name: Enable playback of recordings on iOS
  lineinfile:
    path: /usr/local/bigbluebutton/core/scripts/presentation.yml
    regexp: '^# - mp4'
    line: '- mp4'

- name: Copy default pdf
  copy:
    src: "{{ playbook_dir }}/files/default.pdf"
    dest: /var/www/bigbluebutton-default/
    owner: root
    group: root
    mode: '0755'

#- name: Removendo favicon default
#  ansible.builtin.file:
#    path: /var/www/bigbluebutton-default/images/favicon.png
#    state: absent

- name: Copy favicon
  copy:
    src: "{{ playbook_dir }}/files/favicon.ico"
    dest: /var/www/bigbluebutton-default/

- name: Copy logo
  copy:
    src: "{{ playbook_dir }}/files/logo.png"
    dest: /var/bigbluebutton/playback/presentation/2.0/
    owner: bigbluebutton
    group: bigbluebutton

- name: Copy and extract audio (pt_BR)
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/files/en.zip"
    dest: /opt/freeswitch/share/freeswitch/sounds/

- name: Recursively change ownership of a directory of audio (pt_BR)
  file:
    path: /opt/freeswitch/share/freeswitch/sounds/en
    state: directory
    recurse: yes
    owner: freeswitch
    group: daemon
    mode: '0755'

- name: "Check if log exist"
  stat:
    path: "/var/log/bigbluebutton/bbb-rap-worker.log"
  register: log_bbb_worker

- name: Fix logs permissions (bbb-rap-worker)
  file:
    path: /var/log/bigbluebutton/bbb-rap-worker.log
    owner: bigbluebutton
    group: bigbluebutton
  when: log_bbb_worker.stat.exists

- name: "Check if log exist"
  stat:
    path: "/var/log/bigbluebutton/post_publish.log"
  register: log_post_publish

- name: Fix logs permissions (post_publish)
  file:
    path: /var/log/bigbluebutton/post_publish.log
    owner: bigbluebutton
    group: bigbluebutton
  when: log_post_publish.stat.exists

- name: "Check if log exist"
  stat:
    path: "/var/log/bigbluebutton/sanity.log"
  register: log_sanity

- name: Fix logs permissions (sanity.log)
  file:
    path: /var/log/bigbluebutton/sanity.log
    owner: bigbluebutton
    group: bigbluebutton
  when: log_sanity.stat.exists

- name: Copy cron bbb-recording-cleanup
  copy:
    src: "{{ playbook_dir }}/files/bbb-recording-cleanup"
    dest: /etc/cron.daily/
    mode: '0755'

- name: Instalação as gems necessarias para o Download 
  gem: name={{ item }}
  loop:
    - builder
    - optimist
    - loofah
    - nokogiri
    - redis
    - journald-logger
    - open4
    - absolute_time
    - rest-client

#- name: Modify settings.yml (clientTitle, copyright, helpLink)
#  lineinfile:
#    path=/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
#    regexp={{ item.regexp }}
#    line={{ item.line }}
#    backrefs=yes
#  with_items:
#    - { regexp: '^    clientTitle:', line: '    clientTitle: {{ CLIENT_TITLE }}' }
#    - { regexp: '^    copyright:', line: '    copyright: {{ COPYRIGHT }}' }
#    - { regexp: '^    helpLink:', line: '    helpLink: {{ SUPPORT_URL }}' }

- name: Modify layout
  lineinfile:
    path: /usr/share/meteor/bundle/programs/web.browser/head.html
    regexp: '^  <\/style>'
    line: '    header[class^="navbar"] { background: #003e7a; } </style>'

#- name: Fix webcam problem
#  lineinfile:
#    path: /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
#    regexp: '^;iceTcp=1'
#    line: 'iceTcp=0'

- name: copy bbb-web.properties
  copy:
    src: "{{ playbook_dir }}/files/bbb-web.properties"
    dest: /etc/bigbluebutton/
    owner: bigbluebutton
    group: bigbluebutton

- name: copy bbb-html5.yml
  copy:
    src: "{{ playbook_dir }}/files/bbb-html5.yml"
    dest: /etc/bigbluebutton/
    owner: bigbluebutton
    group: bigbluebutton

- name: Modify bigbluebutton.properties
  lineinfile:
    path=/etc/bigbluebutton/bbb-web.properties
    regexp={{ item.regexp }}
    line={{ item.line }}
    backrefs=yes
  with_items:    
    - { regexp: '^bigbluebutton.web.serverURL=', line: 'bigbluebutton.web.serverURL=https://{{ DOMINIO }}' }
    - { regexp: '^bigbluebutton.web.logoutURL=', line: 'bigbluebutton.web.logoutURL={{ FORM_LOGOUT_URL }}' }

- name: Modify bbb-html5
  lineinfile:
    path=/etc/bigbluebutton/bbb-html5.yml
    regexp={{ item.regexp }}
    line={{ item.line }}
    backrefs=yes
  with_items:    
    - { regexp: '    url:', line: '    url: https://{{ DOMINIO }}/pad' }

#- name: copy apply-config.sh
#  copy:
#    src: "{{ playbook_dir }}/files/apply-config.sh"
#    dest: /etc/bigbluebutton/bbb-conf/
#    owner: bigbluebutton
#    group: bigbluebutton
#    mode: a+x

#- name: Changing perm of "apply-config.sh", adding "+x"
#  file: dest=/etc/bigbluebutton/bbb-conf/apply-config.sh mode=a+x

...
