---
- name: [NOVO] Instalando BigBlueButton - Script
  shell: sudo wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-24 -s "{{ DOMINIO }}" -e '{{ EMAIL }}' -c '{{ TURN_SERVER }}:{{ TURN_SECRET }}'

- name: Enable playback of recordings on iOS
  lineinfile:
    path: /usr/local/bigbluebutton/core/scripts/presentation.yml
    regexp: '^# - mp4'
    line: '- mp4'

- name: Copy default pdf
  copy:
    src: "{{ playbook_dir }}/files/default.pdf"
    dest: /var/www/bigbluebutton-default/
    owner: root
    group: root
    mode: '0755'

- name: [NOVO] Removendo favicon default
  ansible.builtin.file:
    path: /var/www/bigbluebutton-default/images/favicon.png
    state: absent

- name: Copy favicon
  copy:
    src: "{{ playbook_dir }}/files/favicon.ico"
    dest: /var/www/bigbluebutton-default/

- name: Copy logo
  copy:
    src: "{{ playbook_dir }}/files/logo.png"
    dest: /var/bigbluebutton/playback/presentation/2.0/
    owner: bigbluebutton
    group: bigbluebutton

- name: Copy and extract audio (pt_BR)
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/files/en.zip"
    dest: /opt/freeswitch/share/freeswitch/sounds/

- name: Recursively change ownership of a directory of audio (pt_BR)
  file:
    path: /opt/freeswitch/share/freeswitch/sounds/en
    state: directory
    recurse: yes
    owner: freeswitch
    group: daemon
    mode: '0755'

- name: Copy cron bbb-recording-cleanup
  copy:
    src: "{{ playbook_dir }}/files/bbb-recording-cleanup"
    dest: /etc/cron.daily/
    mode: '0755'

- name: install rest-client gem 
  command: gem install rest-client

- name: [NOVO] Modify bigbluebutton.properties (defaultWelcomeMessageFooter, logoutURL, joinViaHTML5Client)
  lineinfile:
    path=/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    regexp={{ item.regexp }}
    line={{ item.line }}
    backrefs=yes
  with_items:
    
    - { regexp: '^bigbluebutton.web.serverURL=', line: 'bigbluebutton.web.serverURL= {{ DOMINIO }}' }

    - { regexp: '^defaultWelcomeMessage=', line: 'defaultWelcomeMessage=<br><br>Bem-vindo \u00e0 <b>%%CONFNAME%%</b>!<br><br>Para participar da webconfer\u00eancia, seu computador deve ter, no m\u00ednimo, um <u>processador dual-core com pelo menos 2G de mem\u00f3ria, uma conex\u00e3o de 1Mbits de download e 0.5 Mbits de upload</u>. Voc\u00ea pode testar sua conex\u00e3o usando o <a href="https://speedtest.net" target="_blank" style="color: #1a0dab;"><u><b>speedtest.net</b></u></a>.<br><br>D\u00ea prefer\u00eancia a conex\u00f5es com cabo, redes sem fio podem ocasionar interrup\u00e7\u00f5es no \u00e1udio. Se sua internet estiver boa, o \u00e1udio tiver sido configurado corretamente e, mesmo assim, o seu \u00e1udio apresentar problemas, tente alternar de navegador. S\u00e3o recomendadas as \u00faltimas vers\u00f5es dos navegadores <a href="https://www.mozilla.org/pt-BR/firefox/new/" target="_blank" style="color: #1a0dab;"><u>Firefox</u></a> ou <a href="https://www.google.com.br/chrome/browser/desktop/" target="_blank" style="color: #1a0dab;"><u>Chrome</u></a>.<br><br>Ao final da webconfer\u00eancia, clique em sair, no canto superior direito, e responda ao nosso question\u00e1rio de avalia\u00e7\u00e3o da ferramenta.<br><br><b>Se esta webconfer\u00eancia estiver sendo gravada, a grava\u00e7\u00e3o ser\u00e1 armazenada por 180 dias. Ap\u00f3s este per\u00edodo, ser\u00e1 removida a fim de maximizar o uso da ferramenta em virtude da alta demanda.</b><br><br>Qualquer d\u00favida, problema ou dificuldade na utiliza\u00e7\u00e3o da ferramenta, entre em contato pelo email: {{ SUPPORT_EMAIL }}' }
    - { regexp: '^defaultWelcomeMessageFooter=', line: 'defaultWelcomeMessageFooter=<br>' }
    - { regexp: '^bigbluebutton.web.logoutURL=', line: 'bigbluebutton.web.logoutURL={{ FORM_LOGOUT_URL }}' }

- name: Modify settings.yml (clientTitle, copyright, helpLink)
  lineinfile:
    path=/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    regexp={{ item.regexp }}
    line={{ item.line }}
    backrefs=yes
  with_items:
    - { regexp: '^    clientTitle:', line: '    clientTitle: {{ CLIENT_TITLE }}' }
    - { regexp: '^    copyright:', line: '    copyright: {{ COPYRIGHT }}' }
    - { regexp: '^    helpLink:', line: '    helpLink: {{ SUPPORT_URL }}' }

- name: Modify layout
  lineinfile:
    path: /usr/share/meteor/bundle/programs/web.browser/head.html
    regexp: '^  <\/style>'
    line: '    header[class^="navbar"] { background: #003e7a; } </style>'

- name: Restart bbb
  command: bbb-conf --restart

- name: Check bbb
  command: bbb-conf --check
  register : result

- debug :
    var: result.stdout_lines


...
