---

- name: configurando FQDN
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/hosts
    state: absent
 
- name: alterando hosts
  copy:
    dest: "/etc/hosts"
    content: |
        127.0.0.1 localhost
        127.0.1.1 {{ ansible_hostname }}
        {{ ansible_default_ipv4.address }} {{ DOMINIO }}
        ::1 ip6-localhost ip6-loopback
        fe00::0 ip6-localnet
        ff00::0 ip6-mcastprefix
        ff02::1 ip6-allnodes
        ff02::2 ip6-allrouters     


- name: Debug /etc/hosts
  shell: cat "/etc/hosts"
  register: etc_hosts

- debug :
    var: etc_hosts.stdout_lines

...